title: My first ever page!
author: David C
email: davidacruz@live.com
description: > # this means to ignore newlines until "baseurl:"
  Learning how to use Github pages. Beginner to coding and IT in general.

# social links
twitter_username: cutzxcruz # DO NOT include the @ character, or else the build will fail!
github_username:  dcruz000 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
